services:
  app:
    build: .
    container_name: spring_app
    ports:
      - "${SPRING_PORT}:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}"
      SPRING_DATASOURCE_USERNAME: "${DB_USER}"
      SPRING_DATASOURCE_PASSWORD: "${DB_PASSWORD}"
    depends_on:
      - db